---
fixtures:
  repositories:
    application: https://github.com/opus-codium/puppet-application.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    postgresql: https://github.com/puppetlabs/puppetlabs-postgresql.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
